import type { Event } from "./db";

export const DEMO_EVENTS: Event[] = [
  {
    id: 1,
    title: "Great Fire of London",
    start_date: "1666-09-02",
    end_date: "1666-09-05",
    notes: "A major conflagration that swept through the central parts of London, destroying over 13,000 houses.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 1,
    group_name: "History",
  },
  {
    id: 2,
    title: "US Declaration of Independence",
    start_date: "1776-07-04",
    end_date: null,
    notes: "The Continental Congress adopted the Declaration of Independence, announcing the separation of the thirteen colonies from Great Britain.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 1,
    group_name: "History",
  },
  {
    id: 3,
    title: "First Photograph",
    start_date: "1826-01-01",
    end_date: null,
    notes: "Nicéphore Niépce captured the earliest known surviving photograph, 'View from the Window at Le Gras', using a camera obscura.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 2,
    group_name: "Technology",
  },
  {
    id: 4,
    title: "Telephone Invented",
    start_date: "1876-03-10",
    end_date: null,
    notes: "Alexander Graham Bell made the first successful telephone call, saying 'Mr. Watson, come here, I want to see you.'",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 2,
    group_name: "Technology",
  },
  {
    id: 5,
    title: "Wright Brothers First Flight",
    start_date: "1903-12-17",
    end_date: null,
    notes: "Orville and Wilbur Wright achieved the first powered, sustained, and controlled airplane flight at Kitty Hawk, North Carolina.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 2,
    group_name: "Technology",
  },
  {
    id: 6,
    title: "Titanic Sinks",
    start_date: "1912-04-15",
    end_date: null,
    notes: "The RMS Titanic sank in the North Atlantic Ocean after striking an iceberg during her maiden voyage from Southampton to New York City.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 1,
    group_name: "History",
  },
  {
    id: 7,
    title: "End of World War II",
    start_date: "1945-05-08",
    end_date: "1945-09-02",
    notes: "VE Day (Victory in Europe) on May 8 and VJ Day (Victory over Japan) on September 2 marked the end of the deadliest conflict in human history.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 1,
    group_name: "History",
  },
  {
    id: 8,
    title: "Apollo 11 Moon Landing",
    start_date: "1969-07-20",
    end_date: "1969-07-24",
    notes: "Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon. Armstrong's famous words: 'That's one small step for man, one giant leap for mankind.'",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 3,
    group_name: "Space Exploration",
  },
  {
    id: 9,
    title: "Fall of the Berlin Wall",
    start_date: "1989-11-09",
    end_date: null,
    notes: "The Berlin Wall, which had divided East and West Berlin since 1961, was opened after weeks of civil unrest, marking the beginning of German reunification.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 1,
    group_name: "History",
  },
  {
    id: 10,
    title: "World Wide Web Goes Public",
    start_date: "1993-04-30",
    end_date: null,
    notes: "CERN put the World Wide Web software into the public domain, making it freely available for anyone to use and build upon.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 2,
    group_name: "Technology",
  },
  {
    id: 11,
    title: "First iPhone Released",
    start_date: "2007-06-29",
    end_date: null,
    notes: "Apple released the first iPhone, revolutionizing the smartphone industry with its multi-touch interface and full web browsing capabilities.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 2,
    group_name: "Technology",
  },
  {
    id: 12,
    title: "COVID-19 Pandemic Declared",
    start_date: "2020-03-11",
    end_date: "2023-05-05",
    notes: "The WHO declared COVID-19 a global pandemic. The public health emergency ended in May 2023 after widespread vaccination and declining cases worldwide.",
    created_by: "demo",
    created_at: "2025-01-01T00:00:00Z",
    group_id: 4,
    group_name: "Health",
  },
];

export const DEMO_GROUPS: { id: number; name: string }[] = [
  { id: 1, name: "History" },
  { id: 2, name: "Technology" },
  { id: 3, name: "Space Exploration" },
  { id: 4, name: "Health" },
];
